### PR TITLE
V0.2 dev UI consistency

### LINKED ISSUE #193: [UI] User Interface Consistency
The UI is very inconsistent in terms of font size, spacing, ordering. We need to make this much more consistent because it causes issues with usability.

Main issues:
Aesthetics: 
- when colouring buttons we need to implmement the :hover property as well (see autolamella._stylesheets) so users know they can click it.
- sizing: so many things are different sizes that shouldnt be
- lots of missing / redundant headers. we need to decide when we use a header / when we dont
- tabception is becoming a problem; what are some solutions

Consistency
- ordering should be consistent; e.g. electron on left, ion on right 
- tab order is completely broken
- func, variable names inaccurate, mismatched

Feedback
- needs to provide user more feedback  (e.g. notifications). example is when we are imaaging or moving as this can take a while to resolve (e.g. TESCAN)
- Disabling functionality when not allowed.

### PR DESCRIPTION
**Pull request by LucileNaegele**

### CODE REVIEW

**Comment by patrickcleeve2** [comment]
@LucileNaegele  will check this out tonight

**Review by patrickcleeve2 — CHANGES_REQUESTED** [review]
@LucileNaegele 
- [x] Make stage parameters font-size consistent with rest of widget
- [x] Remove underline from hardware components
- [x] Change GIS to Gas Injection System

otherwise lgtm

**Review by LucileNaegele — COMMENTED** [review]
@patrickcleeve2 fixed it

**Review by patrickcleeve2 — APPROVED** [review]
lgtm merging

**Pull request merged**
