### PR TITLE
Add detector settings to microscope state

### LINKED ISSUE #260: [MIGRATE] Migrate / Add Detector Settings to Microscope State

### PR DESCRIPTION
**Pull request by LucileNaegele**

### CODE REVIEW

**Review by patrickcleeve2 — CHANGES_REQUESTED** [review]
Please add set functionality for TESCAN / DEMO, added for thermo

**Comment by LucileNaegele** [comment]
> Please add set functionality for TESCAN / DEMO, added for thermo

done @patrickcleeve2

**Review by patrickcleeve2 — CHANGES_REQUESTED** [review]
Need to add the set detector settings to set_microscope_state too

like https://github.com/DeMarcoLab/fibsem/blob/555c0d906340bb662b0d91b39718a381fb13c5ae/fibsem/microscope.py#L2177

**Review by patrickcleeve2 — APPROVED** [review]
lgtm

**Pull request merged**
