### PR TITLE
segmentation update

### PR DESCRIPTION
**Pull request by patrickcleeve2**

### CODE REVIEW

**Review by LachieBurne — APPROVED** [review]
Fixed the minor merge conflicts.

**Comment by patrickcleeve2** [comment]
@LachieBurne @LucileNaegele  I will check this out, and merge it. Thanks

**Comment by LachieBurne** [comment]
Sorry, I already accepted the review. I fixed minor merge conflicts,
hopefully I didn't mess anything up. Sorry again I assumed you wanted us to
have a look at it.

**Comment by patrickcleeve2** [comment]
Thanks @LachieBurne @LucileNaegele, all merged

**Pull request merged**
